platform :ios, '26.0'
use_frameworks!

playwire_version = '13.1.0-alpha.4'

abstract_target 'Playwire' do
  pod 'Playwire', playwire_version

  target 'PlaywireObjC' do
  end

  target 'PlaywireSwift' do
  end

  target 'PlaywireSwiftUI' do
  end
end
